sudo: required
services:
  - docker

before_install:
  - docker build -t rajender/react-docker -f Dockerfile.dev .

script:
  - docker run rajender/react-docker yarn run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"